# Generated by Django 5.0.4 on 2024-06-19 02:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avril', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountuser',
            options={'ordering': ('account_user_related_user',)},
        ),
        migrations.RenameField(
            model_name='accountuser',
            old_name='account_user_fulLname',
            new_name='account_user_fullname',
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('c6c3cc41-3911-4bcb-a177-edd8c00c8bec'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_related_user',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_student_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='accountuser',
            index=models.Index(fields=['account_user_id', 'account_user_related_user'], name='avril_accou_account_73575c_idx'),
        ),
    ]
