# Generated by Django 5.0.4 on 2024-06-28 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avril', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('354ce92b-acb5-40c3-83eb-36e120b6c647'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
