# Generated by Django 5.0.4 on 2024-06-26 05:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avril', '0002_alter_accountuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('58f7316f-f3a0-430d-ba20-0bb711d2edf1'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
