# Generated by Django 5.0.4 on 2024-06-26 05:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avril', '0004_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('6e3f8e90-566d-4d4a-aad7-a95a0edd83e6'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
