# Generated by Django 5.0.4 on 2024-06-26 05:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avril', '0005_alter_accountuser_account_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='account_user_id',
            field=models.UUIDField(default=uuid.UUID('c821f063-3e08-4a12-b0a1-36c4c6abfc73'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
