# Generated by Django 5.0.4 on 2024-07-11 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avril', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('a28d4c96-6a96-4fc9-9ec7-841523e67e06'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('be177ed0-5b5f-4e91-8d5d-2444d2b73fe7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
