# Generated by Django 5.0.4 on 2024-07-11 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avril', '0002_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('b582fc33-4740-4bbd-9556-c591bb6d7001'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('8ff41e81-bcd7-489a-9d56-a1603ff106ee'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
