# Generated by Django 5.0.4 on 2024-07-11 11:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avril', '0003_alter_attendingcourse_attending_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendingcourse',
            name='attending_course_id',
            field=models.UUIDField(default=uuid.UUID('faf9cd53-5830-4f47-9891-12813a8ee5f7'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.UUIDField(default=uuid.UUID('733ee0e0-f9f0-40f4-8c71-7bf03e173219'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
